objects/Animal__c.object
<CustomObject>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Character__c.object
<CustomObject>
    <fields>
        <fullName>AnimalFieldName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Animal</label>
        <referenceTo>Animal__c</referenceTo>
        <relationshipLabel>Characters</relationshipLabel>
        <relationshipName>Characters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CharacterController.cls
public class CharacterController 
{	
    public List<Character__c> characters{get; set;}
    public Character__c newCharacter{get; set;}
    public Animal__c knownAnimals{get; set;}
    
    public CharacterController()
    {
        Boolean thing = true;
        selectCharacters();
        //selectAnimals();
        
        newCharacter = new Character__c();
    }
    
    public PageReference addCharacter()
    {
        insert newCharacter;
        newCharacter = new Character__c();
        
        selectCharacters();
        return null;
    }
   /* public PageReference save() 
    {
        for(Character__c character : characters) {
            
        }
        return null;   
    }*/
    
    public void selectCharacters()
    {
        characters = [SELECT id, Nickname__c, AnimalFieldName__c, AnimalFieldName__r.Nickname__c, AnimalFieldName__r.Type__c
                     FROM Character__c];
    }
    /*public void selectAnimals()
    {
        knownAnimals = [SELECT id, Name, Type__c
                  		FROM Animal__c];
    }*/
    
    public Boolean getHasCharacters() 
    {
        selectCharacters();
        return !characters.isEmpty();
    }
}